In [1]:
import torch

In [3]:
N,D =3,4
x=torch.randn(N,D)
y=torch.randn(N,D,requires_grad = True)
z=torch.randn(N,D)

In [4]:
print(x,x.shape)
print(y,y.shape)
print(z,z.shape)

tensor([[ 0.5170, -0.0626,  1.1702, -0.5879],
        [-0.6412,  0.5648, -0.3636, -0.5995],
        [-0.2405,  0.7979,  0.2228, -2.8198]]) torch.Size([3, 4])
tensor([[ 0.9702,  0.4006,  0.3675,  0.3749],
        [-0.6122, -0.1299,  0.0881,  0.5482],
        [ 0.1811, -0.6976,  1.6061, -0.8710]], requires_grad=True) torch.Size([3, 4])
tensor([[ 1.7350,  0.4460, -1.0057,  1.2735],
        [ 2.2071,  0.6265,  0.4200,  0.0087],
        [-0.4133, -0.4714,  0.1565, -0.8615]]) torch.Size([3, 4])


In [15]:
a= torch.mul(x,y)
print(a)
b=torch.add(a,z)
print(b)
b2=torch.add(a,b)
b3=torch.add(b2,z)
c=torch.sum(b3)
print(c)

tensor([[ 0.5016, -0.0251,  0.4300, -0.2204],
        [ 0.3926, -0.0733, -0.0320, -0.3287],
        [-0.0436, -0.5566,  0.3578,  2.4560]], grad_fn=<MulBackward0>)
tensor([[ 2.2366,  0.4209, -0.5757,  1.0531],
        [ 2.5997,  0.5532,  0.3879, -0.3199],
        [-0.4568, -1.0280,  0.5143,  1.5945]], grad_fn=<AddBackward0>)
tensor(13.9593, grad_fn=<SumBackward0>)


In [18]:
print(x.grad)
print(y.grad)
print(z.grad)

None
tensor([[ 1.0340, -0.1251,  2.3405, -1.1759],
        [-1.2825,  1.1296, -0.7273, -1.1991],
        [-0.4811,  1.5958,  0.4456, -5.6396]])
None


In [17]:
c.backward()